# Generated by Django 5.0.1 on 2024-04-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_post_video_url_post_video_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gif',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
    ]
