# Generated by Django 5.0.1 on 2024-04-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_gif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gif',
        ),
        migrations.AddField(
            model_name='post',
            name='is_gif',
            field=models.BooleanField(default=False),
        ),
    ]
